import { Tool, PricingModel, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'text', name: 'Text & Writing', subCategories: ['Copywriting', 'Storytelling', 'Email Assistant', 'SEO'] },
  { id: 'image', name: 'Image Generation', subCategories: ['Art', 'Editing', 'Logos', 'Vectors'] },
  { id: 'video', name: 'Video & Animation', subCategories: ['Generation', 'Editing', 'Avatars', 'Dubbing'] },
  { id: 'audio', name: 'Audio & Speech', subCategories: ['Text to Speech', 'Music', 'Transcription', 'Voice Cloning'] },
  { id: 'code', name: 'Coding Assistant', subCategories: ['Code Generation', 'Debugging', 'Documentation', 'Terminal'] },
  { id: 'business', name: 'Business & Productivity', subCategories: ['Marketing', 'Finance', 'Meeting Assistants', 'Spreadsheets'] },
  { id: 'chat', name: 'Chatbots & Assistants', subCategories: ['General', 'Customer Support', 'Education', 'Search'] },
  { id: '3d', name: '3D & Design', subCategories: ['Modeling', 'Textures', 'Rendering'] },
  { id: 'dev', name: 'Developer Tools', subCategories: ['LLMs', 'Deployment', 'Testing'] },
];

export const MOCK_TOOLS: Tool[] = [
  // --- CHATBOTS & ASSISTANTS ---
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'A conversational AI model by OpenAI capable of understanding and generating human-like text.',
    websiteUrl: 'https://chat.openai.com',
    imageUrl: 'https://logo.clearbit.com/openai.com',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants', 'Text & Writing'],
    features: ['Conversational Interface', 'Code Generation', 'Creative Writing', 'Plugin Support'],
    addedAt: '2022-11-30T00:00:00Z',
    popular: true,
  },
  {
    id: 'claude',
    name: 'Claude 3',
    description: 'A next-generation AI assistant built for work and trained to be safe, accurate, and secure.',
    websiteUrl: 'https://www.anthropic.com',
    imageUrl: 'https://logo.clearbit.com/anthropic.com',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants', 'Text & Writing', 'Coding Assistant'],
    features: ['Large Context Window', 'Safety Focused', 'Document Analysis', 'Coding'],
    addedAt: '2023-03-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    description: 'Google’s most capable and general model, built to be multimodal from the ground up.',
    websiteUrl: 'https://gemini.google.com',
    imageUrl: 'https://logo.clearbit.com/google.com',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants', 'Text & Writing', 'Code'],
    features: ['Multimodal', 'Google Workspace Integration', 'Real-time Info', 'Reasoning'],
    addedAt: '2023-12-06T00:00:00Z',
    popular: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    description: 'Perplexity AI unlocks the power of knowledge with information discovery and sharing.',
    websiteUrl: 'https://www.perplexity.ai',
    imageUrl: 'https://logo.clearbit.com/perplexity.ai',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants', 'Business & Productivity'],
    features: ['Real-time Search', 'Source Citing', 'Follow-up Questions', 'Mobile App'],
    addedAt: '2023-06-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'poe',
    name: 'Poe',
    description: 'Poe lets you ask questions, get instant answers, and have back-and-forth conversations with AI.',
    websiteUrl: 'https://poe.com',
    imageUrl: 'https://logo.clearbit.com/poe.com',
    pricing: PricingModel.Freemium,
    categories: ['Chatbots & Assistants'],
    features: ['Access Multiple Models', 'Create Bots', 'Fast Interface', 'Mobile App'],
    addedAt: '2023-02-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'character-ai',
    name: 'Character.ai',
    description: 'Neural language model chatbot web application that can generate human-like text responses and participate in contextual conversation.',
    websiteUrl: 'https://beta.character.ai',
    imageUrl: 'https://logo.clearbit.com/character.ai',
    pricing: PricingModel.Free,
    categories: ['Chatbots & Assistants'],
    features: ['Persona Creation', 'Roleplay', 'Creative Writing', 'Community Characters'],
    addedAt: '2023-05-01T00:00:00Z',
    popular: true,
  },
   {
    id: 'pi',
    name: 'Pi',
    description: 'A personalized AI, designed to be supportive, smart, and there for you anytime.',
    websiteUrl: 'https://pi.ai',
    imageUrl: 'https://logo.clearbit.com/inflection.ai',
    pricing: PricingModel.Free,
    categories: ['Chatbots & Assistants'],
    features: ['Emotional Intelligence', 'Supportive', 'Conversational', 'Personal Advice'],
    addedAt: '2023-05-15T00:00:00Z',
    popular: false,
  },
  {
    id: 'huggingchat',
    name: 'HuggingChat',
    description: 'Open source alternative to ChatGPT. Powered by Open Assistant and Llama models.',
    websiteUrl: 'https://huggingface.co/chat/',
    imageUrl: 'https://logo.clearbit.com/huggingface.co',
    pricing: PricingModel.Free,
    categories: ['Chatbots & Assistants'],
    features: ['Open Source', 'Privacy Focused', 'Multiple Models', 'Web Search'],
    addedAt: '2023-04-25T00:00:00Z',
    popular: false,
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Incredibly fast AI inference. Experience near-instantaneous responses from LLMs.',
    websiteUrl: 'https://groq.com',
    imageUrl: 'https://logo.clearbit.com/groq.com',
    pricing: PricingModel.Free,
    categories: ['Chatbots & Assistants', 'Developer Tools'],
    features: ['Ultra Low Latency', 'LPU Inference Engine', 'Open Source Models', 'API Access'],
    addedAt: '2024-02-01T00:00:00Z',
    popular: true,
  },

  // --- IMAGE GENERATION ---
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: 'An independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species.',
    websiteUrl: 'https://www.midjourney.com',
    imageUrl: 'https://logo.clearbit.com/midjourney.com',
    pricing: PricingModel.Paid,
    categories: ['Image Generation'],
    features: ['High Fidelity Art', 'Style Mimicry', 'Discord Interface', 'Upscaling'],
    addedAt: '2023-02-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'dalle3',
    name: 'DALL·E 3',
    description: 'AI system that can create realistic images and art from a description in natural language.',
    websiteUrl: 'https://openai.com/dall-e-3',
    imageUrl: 'https://logo.clearbit.com/openai.com',
    pricing: PricingModel.Paid,
    categories: ['Image Generation'],
    features: ['ChatGPT Integration', 'Prompt Adherence', 'High Resolution', 'Safety Guardrails'],
    addedAt: '2023-10-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'stability-ai',
    name: 'Stable Diffusion',
    description: 'A latent text-to-image diffusion model capable of generating photo-realistic images.',
    websiteUrl: 'https://stability.ai',
    imageUrl: 'https://logo.clearbit.com/stability.ai',
    pricing: PricingModel.Free,
    categories: ['Image Generation'],
    features: ['Open Source', 'Local Installation', 'Inpainting', 'Outpainting'],
    addedAt: '2022-08-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'leonardo-ai',
    name: 'Leonardo.Ai',
    description: 'Create production-quality visual assets for your projects with unprecedented quality, speed, and style-consistency.',
    websiteUrl: 'https://leonardo.ai',
    imageUrl: 'https://logo.clearbit.com/leonardo.ai',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation', '3D & Design'],
    features: ['Game Assets', 'Model Training', 'Texture Generation', 'Canvas Editor'],
    addedAt: '2023-06-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'adobe-firefly',
    name: 'Adobe Firefly',
    description: 'Generative AI made for creators. Use simple text prompts to generate images, text effects, and color palettes.',
    websiteUrl: 'https://www.adobe.com/sensei/generative-ai/firefly.html',
    imageUrl: 'https://logo.clearbit.com/adobe.com',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation', '3D & Design'],
    features: ['Commercial Safe', 'Photoshop Integration', 'Text Effects', 'Vector Recolor'],
    addedAt: '2023-04-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'clipdrop',
    name: 'Clipdrop',
    description: 'Create stunning visuals in seconds. The ultimate ecosystem of apps, plugins & resources for all creators.',
    websiteUrl: 'https://clipdrop.co',
    imageUrl: 'https://logo.clearbit.com/clipdrop.co',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation', '3D & Design'],
    features: ['Cleanup', 'Remove Background', 'Relight', 'Image Upscaler'],
    addedAt: '2023-05-10T00:00:00Z',
    popular: false,
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    description: 'A generative AI tool that helps users turn their creative ideas into beautiful images, with strong typography support.',
    websiteUrl: 'https://ideogram.ai',
    imageUrl: 'https://logo.clearbit.com/ideogram.ai',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation'],
    features: ['Typography', 'Logo Design', 'Text Rendering', 'Community Feed'],
    addedAt: '2023-09-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'crayion',
    name: 'Craiyon',
    description: 'AI model that can draw images from any text prompt (formerly DALL-E mini).',
    websiteUrl: 'https://www.craiyon.com',
    imageUrl: 'https://logo.clearbit.com/craiyon.com',
    pricing: PricingModel.Free,
    categories: ['Image Generation'],
    features: ['Free to Use', 'Unlimited Generations', 'Print on Demand', 'Simple Interface'],
    addedAt: '2022-07-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'lexica',
    name: 'Lexica',
    description: 'The Stable Diffusion search engine and art gallery.',
    websiteUrl: 'https://lexica.art',
    imageUrl: 'https://logo.clearbit.com/lexica.art',
    pricing: PricingModel.Free,
    categories: ['Image Generation', 'Chatbots & Assistants'],
    features: ['Image Search', 'Prompt Inspiration', 'Aperture Model', 'High Quality'],
    addedAt: '2022-09-01T00:00:00Z',
    popular: false,
  },

  // --- VIDEO & ANIMATION ---
  {
    id: 'runway-ml',
    name: 'Runway',
    description: 'A multi-modal AI system that can generate novel videos with text, images, or video clips.',
    websiteUrl: 'https://runwayml.com',
    imageUrl: 'https://logo.clearbit.com/runwayml.com',
    pricing: PricingModel.Paid,
    categories: ['Video & Animation'],
    features: ['Text to Video', 'Image to Video', 'Stylization', 'Inpainting'],
    addedAt: '2023-10-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'sora',
    name: 'Sora',
    description: 'OpenAI\'s text-to-video model capable of creating realistic and imaginative scenes from text instructions.',
    websiteUrl: 'https://openai.com/sora',
    imageUrl: 'https://logo.clearbit.com/openai.com',
    pricing: PricingModel.Contact,
    categories: ['Video & Animation'],
    features: ['Photorealistic', 'Complex Scenes', 'Physical Simulation', '60s Video Generation'],
    addedAt: '2024-02-15T00:00:00Z',
    popular: true,
  },
   {
    id: 'pika',
    name: 'Pika Labs',
    description: 'An idea-to-video platform that brings your creativity to motion.',
    websiteUrl: 'https://pika.art',
    imageUrl: 'https://logo.clearbit.com/pika.art',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation'],
    features: ['Text to Video', 'Image Animation', 'Lip Sync', 'Modify Region'],
    addedAt: '2023-12-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    description: 'Create professional AI videos from text in 120 languages.',
    websiteUrl: 'https://www.synthesia.io',
    imageUrl: 'https://logo.clearbit.com/synthesia.io',
    pricing: PricingModel.Paid,
    categories: ['Video & Animation'],
    features: ['AI Avatars', '120+ Languages', 'Screen Recorder', 'Custom Avatars'],
    addedAt: '2023-05-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    description: 'Next-gen video generation platform. Turn text into professional spokesman videos in minutes.',
    websiteUrl: 'https://www.heygen.com',
    imageUrl: 'https://logo.clearbit.com/heygen.com',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation'],
    features: ['Talking Avatar', 'Video Translation', 'Voice Cloning', 'Templates'],
    addedAt: '2023-07-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'd-id',
    name: 'D-ID',
    description: 'The #1 choice for AI-generated video creation. Create photorealistic videos from any face.',
    websiteUrl: 'https://www.d-id.com',
    imageUrl: 'https://logo.clearbit.com/d-id.com',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation'],
    features: ['Live Portrait', 'Speaking Portrait', 'API Access', 'Real-time Streaming'],
    addedAt: '2023-01-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'kaiber',
    name: 'Kaiber',
    description: 'Video generation engine that allows users to create visual stories from their own images and audio.',
    websiteUrl: 'https://kaiber.ai',
    imageUrl: 'https://logo.clearbit.com/kaiber.ai',
    pricing: PricingModel.Paid,
    categories: ['Video & Animation'],
    features: ['Audio Reactivity', 'Style Transfer', 'Animation', 'Spotify Canvas'],
    addedAt: '2023-06-20T00:00:00Z',
    popular: false,
  },
  {
    id: 'descript',
    name: 'Descript',
    description: 'A new kind of video editor for documents, slides, and podcasts.',
    websiteUrl: 'https://www.descript.com',
    imageUrl: 'https://logo.clearbit.com/descript.com',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech', 'Video & Animation'],
    features: ['Overdub', 'Filler Word Removal', 'Transcription-based Editing', 'Screen Recording'],
    addedAt: '2023-04-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'invideo',
    name: 'InVideo',
    description: 'Turn ideas into videos instantly with InVideo AI.',
    websiteUrl: 'https://invideo.io',
    imageUrl: 'https://logo.clearbit.com/invideo.io',
    pricing: PricingModel.Freemium,
    categories: ['Video & Animation', 'Business & Productivity'],
    features: ['Text to Video', 'Stock Media Library', 'Editor', 'Templates'],
    addedAt: '2023-08-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'wonder-dynamics',
    name: 'Wonder Dynamics',
    description: 'An AI tool that automatically animates, lights and composes CG characters into a live-action scene.',
    websiteUrl: 'https://wonderdynamics.com',
    imageUrl: 'https://logo.clearbit.com/wonderdynamics.com',
    pricing: PricingModel.Paid,
    categories: ['Video & Animation', '3D & Design'],
    features: ['VFX', 'Motion Capture', 'Character Replacement', 'No Mocap Suits'],
    addedAt: '2023-05-01T00:00:00Z',
    popular: false,
  },

  // --- AUDIO & SPEECH ---
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'The most realistic and versatile AI speech software. Premier AI text-to-speech.',
    websiteUrl: 'https://elevenlabs.io',
    imageUrl: 'https://logo.clearbit.com/elevenlabs.io',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech'],
    features: ['Voice Cloning', 'Text to Speech', 'Voice Design', 'Long-form Projects'],
    addedAt: '2023-08-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'suno',
    name: 'Suno AI',
    description: 'Suno is building a future where anyone can make great music.',
    websiteUrl: 'https://suno.ai',
    imageUrl: 'https://logo.clearbit.com/suno.ai',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech', 'Video & Animation'],
    features: ['Music Generation', 'Text to Song', 'Instrumental', 'Vocals'],
    addedAt: '2024-01-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'udio',
    name: 'Udio',
    description: 'Make music in seconds. Udio allows you to generate complete songs with lyrics and vocals.',
    websiteUrl: 'https://www.udio.com',
    imageUrl: 'https://logo.clearbit.com/udio.com',
    pricing: PricingModel.Free,
    categories: ['Audio & Speech'],
    features: ['High Fidelity Music', 'Genre Mixing', 'Lyric Generation', 'Remixing'],
    addedAt: '2024-04-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'murf',
    name: 'Murf.ai',
    description: 'Go from text to speech with a versatile AI voice generator. AI voices for podcasts, videos, and professional presentations.',
    websiteUrl: 'https://murf.ai',
    imageUrl: 'https://logo.clearbit.com/murf.ai',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech'],
    features: ['Studio Quality Voices', 'Voice Cloning', 'Video Sync', 'Collaboration'],
    addedAt: '2023-03-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'otter-ai',
    name: 'Otter.ai',
    description: 'Otter records meetings, takes notes in real time, and generates an automated summary.',
    websiteUrl: 'https://otter.ai',
    imageUrl: 'https://logo.clearbit.com/otter.ai',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech', 'Business & Productivity'],
    features: ['Real-time Transcription', 'Meeting Summaries', 'Speaker Identification', 'Zoom Integration'],
    addedAt: '2023-03-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'lovo',
    name: 'Lovo.ai',
    description: 'Award-winning AI Voice Generator and Text to Speech software with 500+ voices in 100+ languages.',
    websiteUrl: 'https://lovo.ai',
    imageUrl: 'https://logo.clearbit.com/lovo.ai',
    pricing: PricingModel.Paid,
    categories: ['Audio & Speech'],
    features: ['Genny', 'Video Editing', 'Voice Cloning', 'Art Generator'],
    addedAt: '2023-02-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'playht',
    name: 'Play.ht',
    description: 'Generate realistic Text to Speech audio using AI. Convert text to audio for free.',
    websiteUrl: 'https://play.ht',
    imageUrl: 'https://logo.clearbit.com/play.ht',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech'],
    features: ['Ultra Realistic', 'Voice Cloning', 'Podcast Hosting', 'SEO Audio'],
    addedAt: '2023-01-15T00:00:00Z',
    popular: false,
  },
  {
    id: 'soundraw',
    name: 'Soundraw',
    description: 'AI music generator. Create and customize royalty-free music.',
    websiteUrl: 'https://soundraw.io',
    imageUrl: 'https://logo.clearbit.com/soundraw.io',
    pricing: PricingModel.Freemium,
    categories: ['Audio & Speech'],
    features: ['Royalty Free', 'Customizable', 'BGM', 'Commercial Use'],
    addedAt: '2022-12-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'boomy',
    name: 'Boomy',
    description: 'Make instant music with Artificial Intelligence and share it with the world.',
    websiteUrl: 'https://boomy.com',
    imageUrl: 'https://logo.clearbit.com/boomy.com',
    pricing: PricingModel.Free,
    categories: ['Audio & Speech'],
    features: ['Instant Music', 'Distribution', 'Royalties', 'Community'],
    addedAt: '2022-11-15T00:00:00Z',
    popular: false,
  },

  // --- CODING ASSISTANT ---
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'Your AI pair programmer. GitHub Copilot uses the OpenAI Codex to suggest code and entire functions in real-time.',
    websiteUrl: 'https://github.com/features/copilot',
    imageUrl: 'https://logo.clearbit.com/github.com',
    pricing: PricingModel.Paid,
    categories: ['Coding Assistant'],
    features: ['IDE Integration', 'Multi-language Support', 'Test Generation', 'Context Awareness'],
    addedAt: '2023-04-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'The AI-first Code Editor. Build software faster with an editor designed for pair-programming with AI.',
    websiteUrl: 'https://cursor.sh',
    imageUrl: 'https://logo.clearbit.com/cursor.sh',
    pricing: PricingModel.Freemium,
    categories: ['Coding Assistant', 'Developer Tools'],
    features: ['VS Code Fork', 'Codebase Chat', 'Auto-debug', 'Command K'],
    addedAt: '2023-09-15T00:00:00Z',
    popular: true,
  },
   {
    id: 'replit',
    name: 'Replit Ghostwriter',
    description: 'An AI-powered pair programmer built into the Replit online IDE.',
    websiteUrl: 'https://replit.com/site/ghostwriter',
    imageUrl: 'https://logo.clearbit.com/replit.com',
    pricing: PricingModel.Paid,
    categories: ['Coding Assistant', 'Developer Tools'],
    features: ['Complete Code', 'Explain Code', 'Generate Code', 'Transform Code'],
    addedAt: '2023-01-10T00:00:00Z',
    popular: false,
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    description: 'AI assistant for software developers that anticipates your coding needs.',
    websiteUrl: 'https://www.tabnine.com',
    imageUrl: 'https://logo.clearbit.com/tabnine.com',
    pricing: PricingModel.Freemium,
    categories: ['Coding Assistant'],
    features: ['Whole-line Completion', 'Full-function Completion', 'Privacy Focused', 'Self-hosted option'],
    addedAt: '2022-06-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'hugging-face',
    name: 'Hugging Face',
    description: 'The AI community building the future. Build, train and deploy state of the art models.',
    websiteUrl: 'https://huggingface.co',
    imageUrl: 'https://logo.clearbit.com/huggingface.co',
    pricing: PricingModel.Free,
    categories: ['Coding Assistant', 'Developer Tools'],
    features: ['Model Hosting', 'Datasets', 'Spaces', 'Community Driven'],
    addedAt: '2022-11-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'codeium',
    name: 'Codeium',
    description: 'Free AI Code Completion & Chat. An alternative to GitHub Copilot.',
    websiteUrl: 'https://codeium.com',
    imageUrl: 'https://logo.clearbit.com/codeium.com',
    pricing: PricingModel.Free,
    categories: ['Coding Assistant'],
    features: ['Free for Individuals', '20+ Languages', 'IDE Extensions', 'Chat'],
    addedAt: '2023-03-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'blackbox',
    name: 'Blackbox AI',
    description: 'AI coding assistant to help developers code faster.',
    websiteUrl: 'https://www.useblackbox.io',
    imageUrl: 'https://logo.clearbit.com/useblackbox.io',
    pricing: PricingModel.Freemium,
    categories: ['Coding Assistant'],
    features: ['Code Search', 'Code Autocomplete', 'Extract Code from Video', 'Chat'],
    addedAt: '2022-05-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'amazon-codewhisperer',
    name: 'Amazon CodeWhisperer',
    description: 'Build applications faster with the ML-powered coding companion.',
    websiteUrl: 'https://aws.amazon.com/codewhisperer/',
    imageUrl: 'https://logo.clearbit.com/amazon.com',
    pricing: PricingModel.Free,
    categories: ['Coding Assistant'],
    features: ['AWS Integration', 'Security Scans', 'Free Tier', 'Reference Tracking'],
    addedAt: '2023-04-15T00:00:00Z',
    popular: false,
  },

  // --- TEXT & WRITING ---
  {
    id: 'jasper',
    name: 'Jasper',
    description: 'AI Copywriter that helps you write blog posts, social media posts, and marketing copy.',
    websiteUrl: 'https://www.jasper.ai',
    imageUrl: 'https://logo.clearbit.com/jasper.ai',
    pricing: PricingModel.Paid,
    categories: ['Text & Writing', 'Business & Productivity'],
    features: ['50+ Templates', 'Boss Mode', 'Grammarly Integration', 'SEO Surfer Integration'],
    addedAt: '2023-03-05T00:00:00Z',
    popular: true,
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    description: 'Chat by Copy.ai is an AI powered chat bot that helps you write content.',
    websiteUrl: 'https://www.copy.ai',
    imageUrl: 'https://logo.clearbit.com/copy.ai',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing', 'Business & Productivity'],
    features: ['Blog Content', 'Social Media Posts', 'Email Marketing', '90+ Tools'],
    addedAt: '2023-01-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    description: 'Cloud-based typing assistant that reviews spelling, grammar, punctuation, clarity, and delivery mistakes.',
    websiteUrl: 'https://www.grammarly.com',
    imageUrl: 'https://logo.clearbit.com/grammarly.com',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing', 'Business & Productivity'],
    features: ['Grammar Checking', 'Tone Detection', 'Plagiarism Checker', 'Generative AI'],
    addedAt: '2023-04-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'quillbot',
    name: 'QuillBot',
    description: 'AI-powered paraphrasing tool that helps you rewrite and enhance any sentence, paragraph, or article.',
    websiteUrl: 'https://quillbot.com',
    imageUrl: 'https://logo.clearbit.com/quillbot.com',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing'],
    features: ['Paraphraser', 'Grammar Checker', 'Summarizer', 'Citation Generator'],
    addedAt: '2023-02-15T00:00:00Z',
    popular: true,
  },
  {
    id: 'writesonic',
    name: 'Writesonic',
    description: 'Best AI Writer for SEO Blogs, Facebook Ads, Google Ads, and Shopify Products.',
    websiteUrl: 'https://writesonic.com',
    imageUrl: 'https://logo.clearbit.com/writesonic.com',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing', 'Business & Productivity'],
    features: ['SEO Optimized', 'Article Writer', 'Landing Pages', 'Paraphrasing'],
    addedAt: '2023-03-20T00:00:00Z',
    popular: false,
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    description: 'Access the limitless power of AI, right inside Notion. Work faster. Write better.',
    websiteUrl: 'https://www.notion.so/product/ai',
    imageUrl: 'https://logo.clearbit.com/notion.so',
    pricing: PricingModel.Paid,
    categories: ['Business & Productivity', 'Text & Writing'],
    features: ['Summarization', 'Translation', 'Brainstorming', 'Editor Integration'],
    addedAt: '2023-02-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'sudowrite',
    name: 'Sudowrite',
    description: 'The non-judgmental, always-there AI writing partner. Great for fiction and creative writing.',
    websiteUrl: 'https://www.sudowrite.com',
    imageUrl: 'https://logo.clearbit.com/sudowrite.com',
    pricing: PricingModel.Paid,
    categories: ['Text & Writing'],
    features: ['Story Engine', 'Rewrite', 'Brainstorm', 'Character Generator'],
    addedAt: '2022-10-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'rytr',
    name: 'Rytr',
    description: 'An AI writing assistant that helps you create high-quality content, in just a few seconds, at a fraction of the cost.',
    websiteUrl: 'https://rytr.me',
    imageUrl: 'https://logo.clearbit.com/rytr.me',
    pricing: PricingModel.Freemium,
    categories: ['Text & Writing'],
    features: ['40+ Use Cases', '30+ Languages', 'SEO Analyzer', 'Chrome Extension'],
    addedAt: '2022-09-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'novelai',
    name: 'NovelAI',
    description: 'A monthly subscription service for AI-assisted authorship, storytelling, virtual companionship.',
    websiteUrl: 'https://novelai.net',
    imageUrl: 'https://logo.clearbit.com/novelai.net',
    pricing: PricingModel.Paid,
    categories: ['Text & Writing', 'Chatbots & Assistants'],
    features: ['Storytelling', 'Image Generation', 'Text Adventure', 'Modules'],
    addedAt: '2022-08-01T00:00:00Z',
    popular: false,
  },

  // --- BUSINESS & PRODUCTIVITY ---
  {
    id: 'gamma',
    name: 'Gamma',
    description: 'A new medium for presenting ideas. Powered by AI. Create beautiful, engaging content with none of the formatting work.',
    websiteUrl: 'https://gamma.app',
    imageUrl: 'https://logo.clearbit.com/gamma.app',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity', '3D & Design'],
    features: ['Presentation Generation', 'Document to Slides', 'Interactive Elements', 'Analytics'],
    addedAt: '2023-07-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'tome',
    name: 'Tome',
    description: 'The AI-powered storytelling format. Unlock your best work with Tome\'s AI-powered storytelling format.',
    websiteUrl: 'https://tome.app',
    imageUrl: 'https://logo.clearbit.com/tome.app',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity', 'Text & Writing'],
    features: ['Narrative Generation', 'Image Generation', 'Interactive Embeds', 'Mobile Friendly'],
    addedAt: '2023-03-20T00:00:00Z',
    popular: true,
  },
  {
    id: 'fireflies',
    name: 'Fireflies.ai',
    description: 'Automate your meeting notes. Fireflies.ai helps your team record, transcribe, search, and analyze voice conversations.',
    websiteUrl: 'https://fireflies.ai',
    imageUrl: 'https://logo.clearbit.com/fireflies.ai',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity', 'Audio & Speech'],
    features: ['Meeting Recorder', 'Transcription', 'AI Summaries', 'CRM Integrations'],
    addedAt: '2023-04-05T00:00:00Z',
    popular: false,
  },
  {
    id: 'mem',
    name: 'Mem',
    description: 'Mem is the self-organizing workspace for your team. It’s the world’s first AI-powered workspace.',
    websiteUrl: 'https://mem.ai',
    imageUrl: 'https://logo.clearbit.com/mem.ai',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity'],
    features: ['Self-organizing', 'Knowledge Retrieval', 'Smart Write', 'Team Collaboration'],
    addedAt: '2023-05-10T00:00:00Z',
    popular: false,
  },
  {
    id: 'beautiful-ai',
    name: 'Beautiful.ai',
    description: 'Presentation software that designs for you. Create meaningful pitches and reports without putting other work on hold.',
    websiteUrl: 'https://www.beautiful.ai',
    imageUrl: 'https://logo.clearbit.com/beautiful.ai',
    pricing: PricingModel.Paid,
    categories: ['Business & Productivity', '3D & Design'],
    features: ['Smart Templates', 'Brand Controls', 'Analytics', 'Collaboration'],
    addedAt: '2023-01-25T00:00:00Z',
    popular: false,
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Automation that moves you forward. Zapier connects your apps and services to automate repetitive tasks.',
    websiteUrl: 'https://zapier.com',
    imageUrl: 'https://logo.clearbit.com/zapier.com',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity', 'Developer Tools'],
    features: ['App Integration', 'No-code Automation', 'AI Actions', 'Canvas'],
    addedAt: '2023-06-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'canva-magic',
    name: 'Canva Magic',
    description: 'AI-powered design tools integrated into the Canva suite.',
    websiteUrl: 'https://www.canva.com',
    imageUrl: 'https://logo.clearbit.com/canva.com',
    pricing: PricingModel.Freemium,
    categories: ['Image Generation', 'Business & Productivity', '3D & Design'],
    features: ['Template Generation', 'Magic Edit', 'Text to Image', 'Brand Consistency'],
    addedAt: '2023-09-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'fathom',
    name: 'Fathom',
    description: 'Fathom records, transcribes, highlights, and summarizes your meetings so you can focus on the conversation.',
    websiteUrl: 'https://fathom.video',
    imageUrl: 'https://logo.clearbit.com/fathom.video',
    pricing: PricingModel.Free,
    categories: ['Business & Productivity', 'Audio & Speech'],
    features: ['Zoom/Google Meet/Teams', 'Auto Summaries', 'Share Clips', 'Sync to CRM'],
    addedAt: '2023-02-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'browse-ai',
    name: 'Browse AI',
    description: 'The easiest way to extract and monitor data from any website.',
    websiteUrl: 'https://www.browse.ai',
    imageUrl: 'https://logo.clearbit.com/browse.ai',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity', 'Developer Tools'],
    features: ['Web Scraping', 'No Code', 'Monitoring', 'API'],
    addedAt: '2022-11-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'taskade',
    name: 'Taskade',
    description: 'AI-powered productivity. Outline tasks, notes, generate mind maps, and chat with AI.',
    websiteUrl: 'https://www.taskade.com',
    imageUrl: 'https://logo.clearbit.com/taskade.com',
    pricing: PricingModel.Freemium,
    categories: ['Business & Productivity'],
    features: ['AI Assistant', 'Mind Maps', 'Project Management', 'Real-time Collab'],
    addedAt: '2022-12-01T00:00:00Z',
    popular: false,
  },

  // --- OTHERS & 3D & DESIGN ---
  {
    id: 'lumalabs',
    name: 'Luma AI',
    description: 'Capture the world in lifelike 3D. Unmatched photorealism, reflections, and details.',
    websiteUrl: 'https://lumalabs.ai',
    imageUrl: 'https://logo.clearbit.com/lumalabs.ai',
    pricing: PricingModel.Free,
    categories: ['3D & Design', 'Video & Animation'],
    features: ['NeRF Technology', 'Video to 3D', 'Genie 3D Generator', 'Interactive Scenes'],
    addedAt: '2023-11-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'spline',
    name: 'Spline',
    description: 'Spline is a free 3D design tool with real-time collaboration to create web interactive experiences in the browser.',
    websiteUrl: 'https://spline.design',
    imageUrl: 'https://logo.clearbit.com/spline.design',
    pricing: PricingModel.Freemium,
    categories: ['3D & Design'],
    features: ['AI Texture', 'AI Style Transfer', '3D Modeling', 'Web Embed'],
    addedAt: '2023-04-10T00:00:00Z',
    popular: true,
  },
  {
    id: 'blockade-labs',
    name: 'Blockade Labs',
    description: 'Create 360° skybox worlds with AI. Skybox AI is a free tool for creating skybox environments.',
    websiteUrl: 'https://www.blockadelabs.com',
    imageUrl: 'https://logo.clearbit.com/blockadelabs.com',
    pricing: PricingModel.Freemium,
    categories: ['3D & Design', 'Image Generation'],
    features: ['360 Panoramas', 'Skybox Generation', 'VR Ready', 'Sketch to Skybox'],
    addedAt: '2023-07-20T00:00:00Z',
    popular: false,
  },
  {
    id: 'looka',
    name: 'Looka',
    description: 'Design a logo and build a brand you love with AI.',
    websiteUrl: 'https://looka.com',
    imageUrl: 'https://logo.clearbit.com/looka.com',
    pricing: PricingModel.Paid,
    categories: ['3D & Design', 'Image Generation'],
    features: ['Logo Maker', 'Brand Kit', 'Social Media Assets', 'Business Cards'],
    addedAt: '2022-06-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'namelix',
    name: 'Namelix',
    description: 'Business name generator. Generate a short, brandable business name using artificial intelligence.',
    websiteUrl: 'https://namelix.com',
    imageUrl: 'https://logo.clearbit.com/namelix.com',
    pricing: PricingModel.Free,
    categories: ['Business & Productivity'],
    features: ['Name Generation', 'Logo Ideas', 'Domain Check', 'Brandable Names'],
    addedAt: '2022-05-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'uizard',
    name: 'Uizard',
    description: 'Design wireframes, mockups, and prototypes in minutes. Scan sketches and transform them into designs.',
    websiteUrl: 'https://uizard.io',
    imageUrl: 'https://logo.clearbit.com/uizard.io',
    pricing: PricingModel.Freemium,
    categories: ['3D & Design', 'Business & Productivity'],
    features: ['Sketch to Design', 'Screenshot to Design', 'Text to Design', 'Collaboration'],
    addedAt: '2023-01-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'galileo',
    name: 'Galileo AI',
    description: 'Copilot for interface design. Generate complex UI designs from simple text prompts.',
    websiteUrl: 'https://www.usegalileo.ai',
    imageUrl: 'https://logo.clearbit.com/usegalileo.ai',
    pricing: PricingModel.Paid,
    categories: ['3D & Design', 'Developer Tools'],
    features: ['Text to UI', 'Figma Export', 'Mobile & Web', 'High Fidelity'],
    addedAt: '2023-08-01T00:00:00Z',
    popular: false,
  },
  
  // --- DEVELOPER TOOLS & LLMs ---
  {
    id: 'langchain',
    name: 'LangChain',
    description: 'Building applications with LLMs through composability.',
    websiteUrl: 'https://langchain.com',
    imageUrl: 'https://logo.clearbit.com/langchain.com',
    pricing: PricingModel.Free,
    categories: ['Developer Tools'],
    features: ['Framework', 'Python & JS', 'Chains', 'Agents'],
    addedAt: '2022-11-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'pinecone',
    name: 'Pinecone',
    description: 'Vector database for high-performance AI applications.',
    websiteUrl: 'https://www.pinecone.io',
    imageUrl: 'https://logo.clearbit.com/pinecone.io',
    pricing: PricingModel.Freemium,
    categories: ['Developer Tools'],
    features: ['Vector Search', 'Managed Service', 'Scalable', 'Low Latency'],
    addedAt: '2022-10-01T00:00:00Z',
    popular: false,
  },
  {
    id: 'vercel-ai-sdk',
    name: 'Vercel AI SDK',
    description: 'The AI SDK is an open-source library for building AI-powered user interfaces.',
    websiteUrl: 'https://sdk.vercel.ai',
    imageUrl: 'https://logo.clearbit.com/vercel.com',
    pricing: PricingModel.Free,
    categories: ['Developer Tools'],
    features: ['Streaming', 'React Hooks', 'Svelte/Vue Support', 'Edge Compatible'],
    addedAt: '2023-06-01T00:00:00Z',
    popular: true,
  },
  {
    id: 'openai-api',
    name: 'OpenAI API',
    description: 'Access OpenAI\'s powerful models like GPT-4 and DALL·E via a simple API.',
    websiteUrl: 'https://openai.com/api/',
    imageUrl: 'https://logo.clearbit.com/openai.com',
    pricing: PricingModel.Paid,
    categories: ['Developer Tools'],
    features: ['Text Completion', 'Embeddings', 'Fine-tuning', 'Function Calling'],
    addedAt: '2021-01-01T00:00:00Z',
    popular: true,
  }
];